server:
  port: 8080

dingTalk:
  agentId: 1355272313
  appKey: dingfsmxe3tw84dkrlpn
  appSecret: deNlF5xOeTN0bcVsYWvJrOV0YA_tbJfITQWb4dX4LcH_SQwhN5-ssawZ4QWvp4W-
  corpId: ding9f50b15bccd16741
yida:
  #宜搭的应用编码 每个应用都不一致 需要自行配置
  appCode: APP_T1ALOI2OMHEMJ3JNX7HP
  #宜搭的应用密钥  每个应用都不一致 需要自行配置
  appSecretKey: 9X866BD17MFWVQBLZJAJKWW58Z9P1LTUISIXKRG
  commodityFormId: FORM-K5A66M71BMEWEDO92N2OTDK58JUK3N5GRHIXK45
  customerFormId: FORM-K5A66M71BMEWEDO92N2OTDK58JUK3N5GRHIXK65
  orderbillFormId: FORM-K5A66M71BMEWEDO92N2OTDK58JUK3N5GRHIXK95