server:
  port: ${port}

dingTalk:
  #钉钉管理后台查看该企业的信息
  agentId: ${agentId}
  appKey: ${appKey}
  appSecret: ${appSecret}
  corpId: ${corpId}
yida:
  #宜搭的应用编码 每个应用都不一致 需要自行配置
  appCode: ${appCode}
  #宜搭的应用密钥  每个应用都不一致 需要自行配置
  appSecretKey: ${appSecretKey}
  #订货单表单id
  orderFormId: ${orderFormId}